// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	items "belanja-online/internal/items"

	mock "github.com/stretchr/testify/mock"
)

// ItemServiceI is an autogenerated mock type for the ItemServiceI type
type ItemServiceI struct {
	mock.Mock
}

// Search provides a mock function with given fields: name, page, limit
func (_m *ItemServiceI) Search(name string, page int, limit int) ([]items.Item, error) {
	ret := _m.Called(name, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []items.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, int) ([]items.Item, error)); ok {
		return rf(name, page, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) []items.Item); ok {
		r0 = rf(name, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]items.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(name, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewItemServiceI creates a new instance of ItemServiceI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewItemServiceI(t interface {
	mock.TestingT
	Cleanup(func())
}) *ItemServiceI {
	mock := &ItemServiceI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
