// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	items "belanja-online/internal/items"

	mock "github.com/stretchr/testify/mock"
)

// ItemRepositoryI is an autogenerated mock type for the ItemRepositoryI type
type ItemRepositoryI struct {
	mock.Mock
}

// Find provides a mock function with given fields: name, limit, offset
func (_m *ItemRepositoryI) Find(name string, limit int, offset int) ([]items.Item, error) {
	ret := _m.Called(name, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []items.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, int) ([]items.Item, error)); ok {
		return rf(name, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) []items.Item); ok {
		r0 = rf(name, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]items.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(name, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewItemRepositoryI creates a new instance of ItemRepositoryI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewItemRepositoryI(t interface {
	mock.TestingT
	Cleanup(func())
}) *ItemRepositoryI {
	mock := &ItemRepositoryI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
