// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	cart "belanja-online/internal/cart"

	mock "github.com/stretchr/testify/mock"
)

// CartRepositoryI is an autogenerated mock type for the CartRepositoryI type
type CartRepositoryI struct {
	mock.Mock
}

// Add provides a mock function with given fields: itemID, amount
func (_m *CartRepositoryI) Add(itemID int, amount int) error {
	ret := _m.Called(itemID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(itemID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Clear provides a mock function with no fields
func (_m *CartRepositoryI) Clear() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with no fields
func (_m *CartRepositoryI) List() ([]cart.CartItem, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []cart.CartItem
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]cart.CartItem, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []cart.CartItem); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cart.CartItem)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCartRepositoryI creates a new instance of CartRepositoryI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCartRepositoryI(t interface {
	mock.TestingT
	Cleanup(func())
}) *CartRepositoryI {
	mock := &CartRepositoryI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
